version: "3.8"

services:
  leftrouter:
    build: ./router
    tty: true
    command: bash
    container_name: leftrouter
    networks:
      sharednet:
        ipv4_address: 172.25.0.2
      leftnet:
        ipv4_address: 172.26.0.2
    cap_add:
      - NET_ADMIN

  rightrouter:
    build: ./router
    tty: true
    command: bash
    container_name: rightrouter
    networks:
      sharednet:
        ipv4_address: 172.25.0.3
      rightnet:
        ipv4_address: 172.27.0.2
    cap_add:
      - NET_ADMIN

  sender:
    build: ./endpoint
    tty: true
    command: bash
    container_name: sender
    hostname: sender
    volumes:
      - ./send_log:/logs
    networks:
      leftnet:
        ipv4_address: 172.26.0.3
    cap_add:
      - NET_ADMIN

  receiver:
    build: ./endpoint
    tty: true
    command: bash
    container_name: receiver
    hostname: receiver
    volumes:
      - ./receive_log:/logs
    networks:
      rightnet:
        ipv4_address: 172.27.0.3
    cap_add:
      - NET_ADMIN

networks:
  sharednet:
    name: sharednet
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
  leftnet:
    name: leftnet
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
  rightnet:
    name: rightnet
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
